
#line 3 "<stdout>"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 107
#define YY_END_OF_BUFFER 108
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[382] =
    {   0,
        0,    0,  108,  106,  105,  105,   93,  106,   99,   92,
      106,   87,   88,   97,   96,   84,   95,   91,   98,   50,
       49,   85,   81,  100,   86,  101,  104,   47,   47,   89,
       90,  102,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   82,  103,
       83,   94,  105,   80,    0,   58,    0,   66,   83,   75,
       67,    0,    0,   64,   72,   62,   73,   63,   74,    0,
       53,    1,    2,   65,   54,   50,    0,    0,   50,   50,
        0,   50,   49,   49,   49,   49,   90,   82,   89,   71,
       77,   79,   78,   70,   47,    0,    0,   68,   47,   47,

       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   10,   47,   47,   47,   47,   47,   17,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   69,   76,   58,    0,    0,    0,    0,   51,
        0,    0,   59,    0,   53,    2,    0,   54,    0,   52,
       50,   50,   50,   50,    0,   48,   49,   49,   49,   49,
       61,   60,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   15,   47,   47,   19,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,

       47,   47,    0,    0,    0,    0,    0,   53,    0,   54,
       52,   50,    0,    0,   48,    0,   48,   48,   49,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,    3,
       47,    5,    6,   47,   47,   47,   47,   12,   47,   47,
       16,   47,   20,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   33,   47,   47,    0,    0,
        0,    0,    0,    0,   48,   48,    0,   55,   48,   48,
       47,   47,   39,   47,   47,   47,   47,   47,   47,   47,
        4,    7,   47,   47,   47,   47,   14,   47,   47,   47,
       47,   24,   47,   47,   47,   47,   47,   47,   31,   47,

       47,   35,    0,   56,    0,   57,   55,   48,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   11,
       13,   18,   47,   47,   23,   25,   26,   27,   28,   29,
       47,   47,   47,   56,   57,   47,   47,   38,   47,   47,
       47,   47,   47,   47,   47,   47,    9,   47,   47,   30,
       47,   47,   36,   37,   40,   41,   47,   47,   47,   47,
       46,    8,   21,   22,   32,   34,   47,   43,   47,   47,
       42,   47,   47,   47,   47,   47,   47,   47,   45,   44,
        0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   19,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   34,   34,   36,   34,   37,   34,   38,
       34,   34,   39,   40,   41,   34,   34,   42,   34,   34,
       43,   44,   45,   46,   47,    1,   48,   49,   50,   51,

       52,   53,   54,   55,   56,   34,   57,   58,   59,   60,
       61,   62,   34,   63,   64,   65,   66,   67,   68,   69,
       70,   71,   72,   73,   74,   75,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[76] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    4,    1,    1,
        1,    1,    1,    1,    5,    1,    6,    6,    7,    7,
        1,    1,    1,    1,    1,    3,    7,    7,    7,    7,
        7,    7,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    1,    3,    1,    1,    8,    6,    6,    7,
        7,    7,    6,    8,    8,    8,    8,    8,    8,    9,
        8,    8,    9,    8,    9,    8,    9,    8,    9,    8,
        8,    1,    1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[392] =
    {   0,
        0,    0,  695,  696,   74,   76,  670,   75,   57,   76,
      649,  696,  696,  668,   72,  696,   73,   71,   83,  105,
       96,  666,  696,  128,  666,   68,  696,    0,   96,  696,
      696,  665,  140,  622,  624,   47,   51,   48,   60,  625,
       73,  624,  632,   74,  613,  145,  621,  626,  696,   85,
      696,  696,  141,  696,  126,  179,  138,  696,  696,  696,
      696,  132,  142,  696,  696,  696,  696,  696,  696,  665,
      172,  696,    0,  696,  181,  223,  231,  209,   69,  125,
      664,  144,  238,  152,  136,  156,  696,  696,  696,  654,
      696,  696,  696,  653,    0,  191,  632,  696,   80,  614,

      613,  621,  613,  610,  605,  614,  615,  602,  614,  601,
      616,  603,  609,  595,  596,  594,  597,  594,  591,    0,
      151,  595,  206,  593,  124,  184,  597,  590,  646,  180,
      205,  594,  696,  696,  275,  644,  247,  268,    0,  696,
      274,    0,  696,  281,  696,    0,  303,  696,  288,  307,
      165,  696,  612,  589,    0,  295,  231,  696,  610,  587,
      696,  696,  588,  582,  581,  582,  580,  591,  575,  589,
      573,  569,  573,  585,  580,  568,  101,  582,  580,  576,
      575,  578,    0,  564,  568,    0,  569,  566,  556,  554,
      556,  558,  565,  551,  549,  549,  545,  533,  537,  540,

      539,  528,  327,  367,  311,  413,  329,  356,  349,  417,
      696,  696,  275,  276,  315,  388,  229,  381,  696,  530,
      513,  512,  499,  506,  503,  504,  490,  501,  492,    0,
      494,    0,    0,  485,  493,  482,  489,    0,  483,  480,
        0,  484,    0,  479,  479,  478,  475,  487,  477,  479,
      484,  482,  478,  468,  473,    0,  461,  472,  232,    0,
      259,    0,  459,  468,  243,  696,  360,  472,  487,  464,
      457,  460,    0,  457,  450,  456,  446,  453,  459,  456,
        0,    0,  445,  445,  442,  433,    0,  432,  418,  425,
      414,    0,  421,  416,  418,  402,  405,  407,    0,  398,

      400,    0,  406,  478,  482,  501,  696,  696,  302,  405,
      402,  396,  391,  384,  398,  395,  391,  363,  363,    0,
        0,    0,  375,  363,    0,    0,    0,    0,    0,    0,
      359,  358,  346,  696,  696,  339,  348,    0,  324,  341,
      342,  326,  336,  335,  323,  312,    0,  299,  294,    0,
      307,  302,    0,    0,    0,    0,  289,  282,  292,  277,
        0,    0,    0,    0,    0,    0,  264,    0,  266,  241,
        0,  230,  238,  216,  171,  123,   70,   20,    0,    0,
      696,  559,  568,  572,  579,  586,  595,  600,  602,  604,
      606

    } ;

static yyconst flex_int16_t yy_def[392] =
    {   0,
      381,    1,  381,  381,  381,  381,  381,  382,  381,  381,
      383,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  384,  384,  381,
      381,  381,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  381,  381,
      381,  381,  381,  381,  382,  381,  385,  381,  381,  381,
      381,  383,  386,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  387,  381,  381,  381,  381,  381,  381,  381,
      388,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  384,  382,  383,  381,  384,  384,

      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  381,  381,  381,  381,  381,  382,  389,  381,
      383,  390,  381,  381,  381,  387,  381,  381,  381,  381,
      381,  381,  381,  381,  391,  388,  381,  381,  381,  381,
      381,  381,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,

      384,  384,  382,  382,  383,  383,  381,  381,  381,  381,
      381,  381,  391,  391,  381,  381,  381,  381,  381,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  382,  204,
      383,  206,  381,  381,  381,  381,  381,  381,  381,  381,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,

      384,  384,  381,  381,  381,  381,  381,  381,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  381,  381,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
        0,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381

    } ;

static yyconst flex_uint16_t yy_nxt[772] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   21,   21,
       22,   23,   24,   25,   26,   27,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   29,   28,   28,   28,   28,
       29,   28,   30,    4,   31,   32,   33,   34,   35,   36,
       37,   38,   39,   40,   28,   41,   28,   42,   28,   28,
       28,   28,   43,   44,   45,   46,   47,   48,   28,   28,
       28,   49,   50,   51,   52,   53,   53,   53,   53,   56,
       58,   59,   60,   65,  380,   70,   67,   71,   71,   71,
       71,   93,   94,   72,  110,   66,   68,   69,   73,   61,

       96,  111,  113,   97,  151,  115,   74,  112,  133,  152,
       75,  114,   83,   83,   83,   83,  116,  117,   57,   75,
      118,   76,   76,   77,   77,  120,   78,  379,  124,  125,
       56,   84,  121,   88,  152,   78,   85,  163,  126,  140,
       79,  127,   53,   53,  164,   80,   81,   78,   89,   96,
       90,   91,   97,   86,  138,  138,   78,  134,  141,  141,
      153,   85,   82,  129,  234,  235,   99,  100,  101,   57,
       80,  159,  102,   81,  103,   63,  104,  192,  105,  106,
      135,  135,  154,   96,  152,  378,  107,  157,   71,   71,
       71,   71,  158,  160,  193,   56,  158,   71,   71,   71,

       71,  151,  144,  145,  130,  152,  139,  145,  185,  152,
      142,  147,  148,  157,  136,  186,  148,  158,  377,  136,
      149,  158,  149,  144,  145,  150,  150,  150,  150,  145,
      152,  194,  147,  148,   57,  198,   56,   75,  148,   76,
       76,   77,   77,  199,  137,   75,  195,   77,   77,   77,
       77,   96,   75,   78,   83,   83,   83,   83,   79,  188,
      200,   78,  201,   80,  269,  136,  140,  376,   78,  189,
      190,  158,   56,   84,   78,   57,  135,  135,   85,   96,
       82,  140,   78,  266,  203,  203,  270,  375,   80,   78,
      205,  205,  207,  374,  207,   86,  158,  208,  208,  208,

      208,  373,   63,   85,  150,  150,  150,  150,  266,  214,
      136,   57,  263,  264,  209,  136,  209,   63,  140,  210,
      210,  210,  210,  150,  150,  150,  150,  261,  261,  372,
      215,   56,  216,  371,  370,  217,  263,  264,  211,  369,
      137,  368,  211,  259,  259,  208,  208,  208,  208,  336,
      265,  367,  218,  366,   63,  266,  216,  365,  364,  211,
      217,  363,  337,  362,  211,  210,  210,  210,  210,  361,
       57,   56,  208,  208,  208,  208,  268,  268,  268,  268,
      266,  360,  359,  260,  260,  260,  260,  145,  358,  357,
      356,  145,  355,  260,  260,  260,  260,  260,  260,  267,

      354,  267,  353,  352,  268,  268,  268,  268,  145,  351,
       57,  350,  349,  145,  260,  260,  260,  260,  260,  260,
      140,  266,  304,  304,  304,  304,  348,  347,  346,  262,
      262,  262,  262,  210,  210,  210,  210,  345,  265,  262,
      262,  262,  262,  262,  262,  344,  266,  343,  148,  342,
      341,  340,  148,  339,  338,  333,   63,  332,  331,  330,
      262,  262,  262,  262,  262,  262,  329,  328,  327,  148,
      303,  326,  303,  325,  148,  304,  304,  304,  304,  305,
      324,  305,  323,  322,  306,  306,  306,  306,  268,  268,
      268,  268,  321,  320,  304,  304,  304,  304,  306,  306,

      306,  306,  319,  307,  318,  317,  316,  307,  315,  334,
      314,  313,  312,  334,  311,  310,  309,  306,  306,  306,
      306,  308,  308,  302,  307,  301,  300,  299,  298,  307,
      334,  297,  335,  296,  295,  334,  335,  294,  293,  292,
      291,  290,  289,  288,  287,  286,  285,  284,  283,  282,
      281,  280,  279,  335,  278,  277,  276,  275,  335,   55,
      274,   55,   55,   55,   55,   55,   55,   55,   62,  273,
       62,  272,   62,   62,   62,   62,   62,   95,   95,   95,
       95,   55,   55,  271,   55,  258,  257,   55,   62,   62,
      256,   62,  255,  254,   62,  146,  253,  146,  146,  146,

      146,  146,  146,  146,  156,  156,  156,  204,  204,  206,
      206,  213,  213,  252,  251,  250,  249,  248,  247,  246,
      245,  244,  243,  242,  241,  240,  239,  238,  237,  236,
      233,  232,  231,  230,  229,  228,  227,  226,  225,  224,
      223,  222,  221,  220,  219,  219,  212,  212,   96,  202,
       96,  197,  196,  191,  187,  184,  183,  182,  181,  180,
      179,  178,  177,  176,  175,  174,  173,  172,  171,  170,
      169,  168,  167,  166,  165,   63,  162,  161,  155,  143,
      132,  131,  128,  123,  122,  119,  109,  108,   98,   92,
       87,   64,   63,   54,  381,    3,  381,  381,  381,  381,

      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381
    } ;

static yyconst flex_int16_t yy_chk[772] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,    5,    6,    6,    8,
        9,    9,   10,   15,  378,   18,   17,   18,   18,   18,
       18,   26,   26,   19,   36,   15,   17,   17,   19,   10,

       29,   36,   37,   29,   79,   38,   19,   36,   50,   79,
       21,   37,   21,   21,   21,   21,   38,   39,    8,   20,
       39,   20,   20,   20,   20,   41,   21,  377,   44,   44,
       55,   21,   41,   24,   79,   20,   21,   99,   44,   62,
       20,   44,   53,   53,   99,   20,   20,   21,   24,   46,
       24,   24,   46,   21,   57,   57,   20,   50,   63,   63,
       80,   21,   20,   46,  177,  177,   33,   33,   33,   55,
       20,   85,   33,   20,   33,   62,   33,  125,   33,   33,
       56,   56,   80,   56,   82,  376,   33,   84,   71,   71,
       71,   71,   84,   85,  125,   96,   86,   75,   75,   75,

       75,   82,   71,   71,   46,  151,   57,   71,  121,   82,
       63,   75,   75,   86,   56,  121,   75,   84,  375,   56,
       78,   86,   78,   71,   71,   78,   78,   78,   78,   71,
      151,  126,   75,   75,   96,  130,  259,   76,   75,   76,
       76,   76,   76,  130,   56,   77,  126,   77,   77,   77,
       77,  137,   83,   76,   83,   83,   83,   83,   76,  123,
      131,   77,  131,   76,  217,  137,  261,  374,   83,  123,
      123,  157,  138,   83,   76,  259,  135,  135,   83,  135,
       76,  141,   77,  265,  138,  138,  217,  373,   76,   83,
      141,  141,  144,  372,  144,   83,  157,  144,  144,  144,

      144,  370,  261,   83,  149,  149,  149,  149,  265,  156,
      135,  138,  213,  214,  147,  135,  147,  141,  205,  147,
      147,  147,  147,  150,  150,  150,  150,  205,  205,  369,
      156,  203,  156,  367,  360,  156,  213,  214,  150,  359,
      135,  358,  150,  203,  203,  207,  207,  207,  207,  309,
      215,  357,  156,  352,  205,  215,  156,  351,  349,  150,
      156,  348,  309,  346,  150,  209,  209,  209,  209,  345,
      203,  204,  208,  208,  208,  208,  267,  267,  267,  267,
      215,  344,  343,  204,  204,  204,  204,  208,  342,  341,
      340,  208,  339,  204,  204,  204,  204,  204,  204,  216,

      337,  216,  336,  333,  216,  216,  216,  216,  208,  332,
      204,  331,  324,  208,  204,  204,  204,  204,  204,  204,
      206,  218,  303,  303,  303,  303,  323,  319,  318,  206,
      206,  206,  206,  210,  210,  210,  210,  317,  218,  206,
      206,  206,  206,  206,  206,  316,  218,  315,  210,  314,
      313,  312,  210,  311,  310,  301,  206,  300,  298,  297,
      206,  206,  206,  206,  206,  206,  296,  295,  294,  210,
      263,  293,  263,  291,  210,  263,  263,  263,  263,  264,
      290,  264,  289,  288,  264,  264,  264,  264,  268,  268,
      268,  268,  286,  285,  304,  304,  304,  304,  305,  305,

      305,  305,  284,  268,  283,  280,  279,  268,  278,  304,
      277,  276,  275,  304,  274,  272,  271,  306,  306,  306,
      306,  270,  269,  258,  268,  257,  255,  254,  253,  268,
      304,  252,  306,  251,  250,  304,  306,  249,  248,  247,
      246,  245,  244,  242,  240,  239,  237,  236,  235,  234,
      231,  229,  228,  306,  227,  226,  225,  224,  306,  382,
      223,  382,  382,  382,  382,  382,  382,  382,  383,  222,
      383,  221,  383,  383,  383,  383,  383,  384,  384,  384,
      384,  385,  385,  220,  385,  202,  201,  385,  386,  386,
      200,  386,  199,  198,  386,  387,  197,  387,  387,  387,

      387,  387,  387,  387,  388,  388,  388,  389,  389,  390,
      390,  391,  391,  196,  195,  194,  193,  192,  191,  190,
      189,  188,  187,  185,  184,  182,  181,  180,  179,  178,
      176,  175,  174,  173,  172,  171,  170,  169,  168,  167,
      166,  165,  164,  163,  160,  159,  154,  153,  136,  132,
      129,  128,  127,  124,  122,  119,  118,  117,  116,  115,
      114,  113,  112,  111,  110,  109,  108,  107,  106,  105,
      104,  103,  102,  101,  100,   97,   94,   90,   81,   70,
       48,   47,   45,   43,   42,   40,   35,   34,   32,   25,
       22,   14,   11,    7,    3,  381,  381,  381,  381,  381,

      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#line 28 "lexer.l"
#include "info.h"
#include "y.tab.h"
#include <stdio.h>

static void comment(void);
extern void yyerror(const char *);  /* prints grammar violation message */
static int check_type(void);
extern int sym_type(const char *);  /* returns type from symbol table */

#define sym_type(identifier) IDENTIFIER /* with no symbol table, fake it */

#line 779 "<stdout>"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 41 "lexer.l"

#line 999 "<stdout>"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 382 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 696 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 42 "lexer.l"
{ comment(); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 43 "lexer.l"
{ /* consume //-comment */ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 45 "lexer.l"
{ return(AUTO); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 46 "lexer.l"
{ return(BREAK); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 47 "lexer.l"
{ return(CASE); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 48 "lexer.l"
{ return(CHAR); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 49 "lexer.l"
{ return(CONST); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 50 "lexer.l"
{ return(CONTINUE); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 51 "lexer.l"
{ return(DEFAULT); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 52 "lexer.l"
{ return(DO); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 53 "lexer.l"
{ return(DOUBLE); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 54 "lexer.l"
{ return(ELSE); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 55 "lexer.l"
{ return(EXTERN); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 56 "lexer.l"
{ return(FLOAT); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 57 "lexer.l"
{ return(FOR); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 58 "lexer.l"
{ return(GOTO); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 59 "lexer.l"
{ return(IF); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 60 "lexer.l"
{ return(INLINE); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 61 "lexer.l"
{ return(INT); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 62 "lexer.l"
{ return(LONG); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 63 "lexer.l"
{ return(REGISTER); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 64 "lexer.l"
{ return(RESTRICT); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 65 "lexer.l"
{ return(RETURN); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 66 "lexer.l"
{ return(SHORT); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 67 "lexer.l"
{ return(SIGNED); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 68 "lexer.l"
{ return(SIZEOF); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 69 "lexer.l"
{ return(STATIC); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 70 "lexer.l"
{ return(STRUCT); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 71 "lexer.l"
{ return(SWITCH); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 72 "lexer.l"
{ return(TYPEDEF); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 73 "lexer.l"
{ return(UNION); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 74 "lexer.l"
{ return(UNSIGNED); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 75 "lexer.l"
{ return(VOID); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 76 "lexer.l"
{ return(VOLATILE); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 77 "lexer.l"
{ return(WHILE); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 78 "lexer.l"
{ return ALIGNAS; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 79 "lexer.l"
{ return ALIGNOF; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 80 "lexer.l"
{ return ATOMIC; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 81 "lexer.l"
{ return BOOL; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 82 "lexer.l"
{ return COMPLEX; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 83 "lexer.l"
{ return GENERIC; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 84 "lexer.l"
{ return IMAGINARY; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 85 "lexer.l"
{ return NORETURN; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 86 "lexer.l"
{ return STATIC_ASSERT; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 87 "lexer.l"
{ return THREAD_LOCAL; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 88 "lexer.l"
{ return FUNC_NAME; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 90 "lexer.l"
{ return check_type(); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 92 "lexer.l"
{ yylval.intval = atoi(yytext); return I_CONSTANT; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 93 "lexer.l"
{ yylval.intval = atoi(yytext); return I_CONSTANT; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 94 "lexer.l"
{ yylval.intval = atoi(yytext); return I_CONSTANT; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 95 "lexer.l"
{ yylval.intval = atoi(yytext); return I_CONSTANT; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 97 "lexer.l"
{ yylval.doubleval = atof(yytext); return F_CONSTANT; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 98 "lexer.l"
{ yylval.doubleval = atof(yytext); return F_CONSTANT; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 99 "lexer.l"
{ yylval.doubleval = atof(yytext); return F_CONSTANT; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 100 "lexer.l"
{ yylval.doubleval = atof(yytext); return F_CONSTANT; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 101 "lexer.l"
{ yylval.doubleval = atof(yytext); return F_CONSTANT; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 102 "lexer.l"
{ yylval.doubleval = atof(yytext); return F_CONSTANT; }
	YY_BREAK
case 58:
/* rule 58 can match eol */
YY_RULE_SETUP
#line 104 "lexer.l"
{ yylval.pstring = new string(yytext); return STRING_LITERAL; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 106 "lexer.l"
{ return ELLIPSIS; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 107 "lexer.l"
{ return RIGHT_ASSIGN; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 108 "lexer.l"
{ return LEFT_ASSIGN; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 109 "lexer.l"
{ return ADD_ASSIGN; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 110 "lexer.l"
{ return SUB_ASSIGN; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 111 "lexer.l"
{ return MUL_ASSIGN; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 112 "lexer.l"
{ return DIV_ASSIGN; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 113 "lexer.l"
{ return MOD_ASSIGN; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 114 "lexer.l"
{ return AND_ASSIGN; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 115 "lexer.l"
{ return XOR_ASSIGN; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 116 "lexer.l"
{ return OR_ASSIGN; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 117 "lexer.l"
{ return RIGHT_OP; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 118 "lexer.l"
{ return LEFT_OP; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 119 "lexer.l"
{ return INC_OP; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 120 "lexer.l"
{ return DEC_OP; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 121 "lexer.l"
{ return PTR_OP; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 122 "lexer.l"
{ return AND_OP; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 123 "lexer.l"
{ return OR_OP; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 124 "lexer.l"
{ return LE_OP; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 125 "lexer.l"
{ return GE_OP; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 126 "lexer.l"
{ return EQ_OP; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 127 "lexer.l"
{ return NE_OP; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 128 "lexer.l"
{ return ';'; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 129 "lexer.l"
{ return '{'; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 130 "lexer.l"
{ return '}'; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 131 "lexer.l"
{ return ','; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 132 "lexer.l"
{ return ':'; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 133 "lexer.l"
{ return '='; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 134 "lexer.l"
{ return '('; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 135 "lexer.l"
{ return ')'; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 136 "lexer.l"
{ return '['; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 137 "lexer.l"
{ return ']'; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 138 "lexer.l"
{ return '.'; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 139 "lexer.l"
{ return '&'; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 140 "lexer.l"
{ return '!'; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 141 "lexer.l"
{ return '~'; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 142 "lexer.l"
{ return '-'; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 143 "lexer.l"
{ return '+'; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 144 "lexer.l"
{ return '*'; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 145 "lexer.l"
{ return '/'; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 146 "lexer.l"
{ return '%'; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 147 "lexer.l"
{ return '<'; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 148 "lexer.l"
{ return '>'; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 149 "lexer.l"
{ return '^'; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 150 "lexer.l"
{ return '|'; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 151 "lexer.l"
{ return '?'; }
	YY_BREAK
case 105:
/* rule 105 can match eol */
YY_RULE_SETUP
#line 153 "lexer.l"
{ /* whitespace separates tokens */ }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 154 "lexer.l"
{ /* discard bad characters */ }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 156 "lexer.l"
ECHO;
	YY_BREAK
#line 1593 "<stdout>"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 382 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 382 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 381);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 156 "lexer.l"



int yywrap(void)        /* called at end of input */
{
    return 1;           /* terminate now */
}


static void comment(void)
{
    int c;

    while ((c = yyinput()) != 0)
        if (c == '*')
        {
            while ((c = yyinput()) == '*')
                ;

            if (c == '/')
                return;

            if (c == 0)
                break;
        }
    yyerror("unterminated comment");
}

static int check_type(void)
{
    switch (sym_type(yytext))
    {
    case TYPEDEF_NAME:                /* previously defined */
         yylval.pstring = new string(yytext);
         return TYPEDEF_NAME;
    default:                          /* includes undefined */
         yylval.pstring = new string(yytext);
         return IDENTIFIER;
    }
}

